image:
  file: .gitpod.dockerfile
ports:
- port: 8000
  onOpen: open-preview
tasks:
- init: >
    gp env DJANGO_SETTINGS_MODULE=bowls.settings.development &&
    eval $(gp env -e)
    echo "SELECT 'CREATE DATABASE bowls' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'bowls')\gexec" | psql &&
    python -m pip install -r ./requirements/development.txt &&
    python ./app/manage.py migrate &&
    echo "from django.contrib.auth import get_user_model; get_user_model().objects.create_superuser('admin', '', 'changeme')" | python ./app/manage.py shell
  command: >
    python ./app/manage.py runserver 0.0.0.0:8000
vscode:
  extensions:
    - ms-python.python
    - ms-azuretools.vscode-docker