# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_stages: [commit]
default_language_version:
  python: python3.11
exclude: "[a-zA-Z]*/(migrations)/(.)*"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.3.0"
    hooks:
    -   id: trailing-whitespace
        exclude: ".bumpversion.cfg"
    -   id: end-of-file-fixer
        exclude: ".bumpversion.cfg"
    -   id: check-added-large-files
  - repo: https://github.com/abravalheri/validate-pyproject
    rev: "v0.15"
    hooks:
      - id: validate-pyproject
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version. Keep this in sync with the venv installed version
    rev: v0.2.1
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
  - repo: https://github.com/PyCQA/bandit
    rev: "1.7.5"
    hooks:
      - id: bandit
        args:
          - "--quiet"
          - "--configfile=pyproject.toml"
        additional_dependencies: [ "bandit[toml]" ]
  ## These checks for migrations require the database to be available
  # - repo: https://github.com/ecugol/pre-commit-hooks-django
  #   rev: "v0.4.0"
  #   hooks:
  #     - id: check-absent-migrations
  #     - id: check-untracked-migrations
