version: '3'
services:
  db:
    image: bitnami/postgresql:latest
    environment:
      - ALLOW_EMPTY_PASSWORD="no"
      - POSTGRESQL_POSTGRES_PASSWORD=root1234
      - POSTGRESQL_DATABASE=bowls
      - POSTGRESQL_USERNAME=bowls
      - POSTGRESQL_PASSWORD=bowls1234
    networks:
      default:
        aliases:
          - db.localhost

  cache:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      default:
        aliases:
          - redis.localhost

  # SMTP server to capture outgoing emails
  email:
    image: docker.io/mailhog/mailhog
    logging:
      driver: 'none'  # disable to verbose logs
    networks:
      default:
        aliases:
          - mailhog.localhost

  web:
    ports:
      - "5678:5678" # debug port
    image: bowls:devcontainer
    build:
      context: .
      target: devcontainer
    restart: on-failure
    # volumes:
    #   - .:/var/app
    read_only: true
    tmpfs:
      - /var/tmp:mode=770,uid=1000,gid=1000
    depends_on:
      - db
      - email
      - cache
    environment:
      # re-use variables from .env file
      - DJANGO_SETTINGS_MODULE
      - DJANGO_SECRET_KEY
      - DATABASE_URL
    networks:
      default:
        aliases:
          - bowls.localhost

  # celery:
  #   entrypoint: "python -m debugpy --listen 0.0.0.0:5679 -m celery -A config worker -l info --time-limit=300 -O fair"
  #   image: bowls:devcontainer
  #   build:
  #     context: .
  #     target: devcontainer
  #   restart: on-failure
  #   read_only: true
  #   tmpfs:
  #     - /var/tmp:mode=770,uid=1000,gid=1000
  #   depends_on:
  #     - db
  #     - email
  #     - cache
  #   environment:
  #     # re-use variables from .env file
  #     - DJANGO_SETTINGS_MODULE
  #     - DJANGO_SECRET_KEY
  #     - DATABASE_URL

  # beat:
  #   entrypoint: "python -m debugpy --listen 0.0.0.0:5679 -m celery -A config beat"
  #   image: bowls:devcontainer
  #   build:
  #     context: .
  #     target: devcontainer
  #   restart: on-failure
  #   read_only: true
  #   tmpfs:
  #     - /var/tmp:mode=770,uid=1000,gid=1000
  #   depends_on:
  #     - db
  #     - email
  #     - cache
  #   environment:
  #     # re-use variables from .env file
  #     - DJANGO_SETTINGS_MODULE
  #     - DJANGO_SECRET_KEY
  #     - DATABASE_URL
